/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenVoiceRouteImport } from './routes/citizen-voice'
import { Route as DemandRouteImport } from './routes/demand'
import { Route as HotspotRouteImport } from './routes/hotspot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenVoiceRoute = CitizenVoiceRouteImport.update({
  id: '/citizen-voice',
  path: '/citizen-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandRoute = DemandRouteImport.update({
  id: '/demand',
  path: '/demand',
  getParentRoute: () => rootRouteImport,
} as any)
const HotspotRoute = HotspotRouteImport.update({
  id: '/hotspot',
  path: '/hotspot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen-voice': typeof CitizenVoiceRoute
  '/demand': typeof DemandRoute
  '/hotspot': typeof HotspotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen-voice': typeof CitizenVoiceRoute
  '/demand': typeof DemandRoute
  '/hotspot': typeof HotspotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen-voice': typeof CitizenVoiceRoute
  '/demand': typeof DemandRoute
  '/hotspot': typeof HotspotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/citizen-voice' | '/demand' | '/hotspot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/citizen-voice' | '/demand' | '/hotspot'
  id: '__root__' | '/' | '/citizen-voice' | '/demand' | '/hotspot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenVoiceRoute: typeof CitizenVoiceRoute
  DemandRoute: typeof DemandRoute
  HotspotRoute: typeof HotspotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-voice': {
      id: '/citizen-voice'
      path: '/citizen-voice'
      fullPath: '/citizen-voice'
      preLoaderRoute: typeof CitizenVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demand': {
      id: '/demand'
      path: '/demand'
      fullPath: '/demand'
      preLoaderRoute: typeof DemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotspot': {
      id: '/hotspot'
      path: '/hotspot'
      fullPath: '/hotspot'
      preLoaderRoute: typeof HotspotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenVoiceRoute: CitizenVoiceRoute,
  DemandRoute: DemandRoute,
  HotspotRoute: HotspotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
